function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(4)=params(9);
    ys_(3)=params(9);
    ys_(1)=0;
    ys_(2)=0;
    ys_(5)=1/params(2)-1;
    ys_(6)=1/params(2)-1;
    % Auxiliary equations
ys_(7)=exo_(1);
end
